sudo: required

language: java

services:
  - docker

env:
  global:
    - secure: "ALlyTHgM9nLMY737b5ZKK0stiTL/zPH0Bxtk4jVx3DLGwdVY1T+YgmyJMWxV1FKdjexQPHaQYuT+9pnEloqxouQ3l73VZMUeH/HTbukO4UceixSCfELat9cy+h00GB9j/beoZEwBShNLJLvjDcvOYj3OPyHVU9exc6DNttBiuCZiJU6gJSsRnKYLdAWRsn8S0Zlv1QpGaTcvIoJ/ylzpdKIMA39UL/dyCsJxWzapJX+s0X2HXlL63co/TM+ju8sk0i2+DeC+Nm1ERUp2eKvKN5efMLOZYe0s/CZWxsextMtcG4TNQIXUWTbVe66Ft5DHZBqWf5N4Doj3Rvkq0lwScgNqRZsqjfV21QvUjxbi0/NSSFPJM+C0xgfqRxMhl/HTA4UaY3GGGKFGtUTncJpX3KrijwVgN5TGvM2OOGYtxUy1+CSe6XnarO+PsWAUzfDdDAPAOlWO1mDGmpc/Ew9HghGw5UIsvMfBpQ8gVhb6BCx8RaMSaEyENs2UFYdmvE/PZGimo4zKPISGWBXxwcvMYG6vSzTDn3YcCpzz8eKfLfdtqGRy1TeNuLQYqE8Ff5DTWWfA2IwCABOr2hWKEu3q4NF0i8Fl0/7HOWobitOJ5uQSV98qVPhObOV3ewrXCx3m0/a4EcOrDBf2poEXjeTxUGSH5O6n/R1BqSK2NL04aQc="
    - secure: "udhMifYbwy786ToPW/47GGhy4BZnGaZ5BGA30AndygRPHA4kkNI30nrJvhEtM/Qwwr/H1Ln8q2f0QHG83+LhVOJXHk76FRnHe8NHgxrkuwmkQAM7/537yofDlus/+ZqNEqpq6hBooCpSxS0YAQTLq2fwf28CV+9CL3BTI6mCN2gh8u/GR23HE0++dBS6Y9xrjHpUZNAf5MldRtckfk/4cYo6WzyE8Hf0Ga8Fp6Kgj/OFSId9tzdlFlabmYEEMm7sqwu59JOFnkncF8ig/HcDNdQVKksL20Nt1lXrjO2Y6jmr6wbKN0hvFXcBVVgIOZEY0R5YZrSmWITqTsUx3DYx5/6KSGwUUPrgnmSPZZBOgtohRhBYmk/M5eGLdcw23tVe1PD9Jtt/xxOCnXncsnOOZ+vkUNzbwNMyyaxTrJGfetYCC3DNIdiMT64ACaunybh/cbql/accLlascR2iCzFLw2vcpgfmRGNUNSsbTGsfSFJHxHjRAf+Ryiwd0k2IlxTDj/5iTVLdvO1Gutrro0r4ilDXMTxzwcCG/sEU6SQl21Z1OhGxrkTdrjBkWyQ2AMvmFyO+kphohW3qYSC7+onNd5YJTzmPaTngmBtT9U4tbK/M73JvakiPZruGDi+n50ZqqkP8ELmca5s20Hed6lR/HJcbKjzIOlhYtdCVC+HNeYk="
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=jasphall/springbootcd_poc
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
